### ISSUE TITLE
mkDockerManifest: How do you specify the tag & version at runtime?

### ISSUE THREAD

**Issue by antifuchs** [mirkolenz/flocken#3]
I am currently trying to use mkDockerManifest to automate my CI builds (in github actions), so that I can [finally get off Dockerfile-based builds](https://github.com/boinkor-net/tsnsrv/issues/55). This looks great, but I am running into one hurdle: The function as it is right now expects the `version` and other tags to be given to it via nix source code.

Since I'm calling this from a flake, those things like "I'm on a branch and this is its name" aren't really easy to determine... or are they? I'm not sure how I would have that information in source code on a github branch build... but I'd love to have that information so that I can push development tags to ghcr, if needed.

Do you see any way to do that with the code as-is?

Otherwise, I think it might be possible to add `name` and `tags` as CLI arguments to the script that this function writes. What do you think about that option?

**Comment by mirkolenz** [comment]
Hi, that is a great question! Since I assume that this is something most people want to achieve, I added a concrete example to the project's readme. Please have a look and let me know if the information is sufficient for you.

Here is another project of mine where I do the exact thing you are trying to achieve: https://github.com/mirkolenz/grpc-proxy

It may also make sense to extend the script as you suggest and pass those parameters as CLI arguments in the future. For now I would like to keep the script as simple as possible and focus on the nix interface. But this is something I will keep in mind for future major revisions of this function 😄

**Comment by antifuchs** [comment]
Oooh, I didn't realize this was meant to be used with `--impure`! That makes a lot of sense & definitely works for me. Thanks for the example, this is super workable!

**Comment by antifuchs** [comment]
This is completely fantastic. Thanks for the update on the readme, I've gotten my change to work (using cross-compiled packages, which tends to be a bunch faster than running `go build` under qemu). It's fast enough that I can now build & push all platforms even for pull requests (:

**Comment by mirkolenz** [comment]
Great to hear that it works for you! I further highlighted the need for `--impure` so that others will not miss this.

Makes sense to use cross-compiling for go packages. I ran into some issues with it in other repos (like some cross packages not being cached in Hydra) and thus settled on QEMU for all my needs.
